jobs:
  include:
    - stage: build
      script:
      - make build

deploy:
  - provider: script
    env: VERSION=latest
    script: make deploy
    on:
      branch: master
  - provider: script
    env: VERSION=$TRAVIS_TAG
    script: make deploy
    on:
      tags: true


