jobs:
  include:
    - stage: build
      script:
      - make build

deploy:
  - provider: script
    script: make deploy
    on:
      branch: master
  - provider: script
    env: VERSION=$TRAVIS_TAG
    script: make deploy
    on:
      tags: true
# can i sneak another change? what is it for?
